version: "3.9"
   
services:
   web:
     build: .
     command: python manage.py runserver 0.0.0.0:8000
     ports:
       - "8000:8000"
     depends_on:
       - db
       - redis
       - rabbitmq
  db:
    image: mariadb:10.4.8
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root-secure-password"
      MYSQL_USER: "radak_app"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "radak"
    volumes:
      - "./db:/var/lib/mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  redis:
    image: redis:5.0.7
    ports:
      - 6379:6379
#  rabbitmq:
#    image: rabbitmq:3.7.8
#  celery:
#    image: celery
#    restart: on-failure
#    command: celery -A radak beat -l info && celery -A radak worker -l info
#    depends_on:
#      - db
#      - redis
#      - rabbitmq
