config:
  app_name: "nazri"
  db:
    mysql:
      name:     "nazri"
      user:     "nazri_app"
      password: "password"
  cache:
    CACHE_TTL: 3600
  celery:
    redis_broker: false
    rabbitMQ_broker: true
