config:
  app_name: "nazri"
  db:
    mysql:
      name:     "test"
      user:     "test_user"
      password: "password"
    influx:
      name:     "test"
      user:     "test_user"
      password: "password"
      timeout:  10
      token: ""
  cache:
    CACHE_TTL: 3600
  celery:
    redis_broker: false
    rabbitMQ_broker: true
