name: Lint

on: [push]

jobs:
  Lint:
    name: check lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt
          no-deps: true
          pre: true
          upgrade: false

      - name: isort
        run: isort --check-only --skip-glob=.tox --reverse-sort --profile=black .

      - name: linter
        run: blue --check .

      - name: formatter
        run: flake8 --exclude='.tox','__init__.py','venv/','settings.py' --extend-exclude='*_pb2*.py' .
